/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Web3RouteImport } from './routes/web3'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as MatchmakingRouteImport } from './routes/matchmaking'
import { Route as FrontendRouteImport } from './routes/frontend'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as AnotherPageRouteImport } from './routes/anotherPage'
import { Route as IndexRouteImport } from './routes/index'

const Web3Route = Web3RouteImport.update({
  id: '/web3',
  path: '/web3',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakingRoute = MatchmakingRouteImport.update({
  id: '/matchmaking',
  path: '/matchmaking',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendRoute = FrontendRouteImport.update({
  id: '/frontend',
  path: '/frontend',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/buy': typeof BuyRoute
  '/frontend': typeof FrontendRoute
  '/matchmaking': typeof MatchmakingRoute
  '/problems': typeof ProblemsRoute
  '/result': typeof ResultRoute
  '/sql': typeof SqlRoute
  '/web3': typeof Web3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/buy': typeof BuyRoute
  '/frontend': typeof FrontendRoute
  '/matchmaking': typeof MatchmakingRoute
  '/problems': typeof ProblemsRoute
  '/result': typeof ResultRoute
  '/sql': typeof SqlRoute
  '/web3': typeof Web3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/buy': typeof BuyRoute
  '/frontend': typeof FrontendRoute
  '/matchmaking': typeof MatchmakingRoute
  '/problems': typeof ProblemsRoute
  '/result': typeof ResultRoute
  '/sql': typeof SqlRoute
  '/web3': typeof Web3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotherPage'
    | '/buy'
    | '/frontend'
    | '/matchmaking'
    | '/problems'
    | '/result'
    | '/sql'
    | '/web3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anotherPage'
    | '/buy'
    | '/frontend'
    | '/matchmaking'
    | '/problems'
    | '/result'
    | '/sql'
    | '/web3'
  id:
    | '__root__'
    | '/'
    | '/anotherPage'
    | '/buy'
    | '/frontend'
    | '/matchmaking'
    | '/problems'
    | '/result'
    | '/sql'
    | '/web3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotherPageRoute: typeof AnotherPageRoute
  BuyRoute: typeof BuyRoute
  FrontendRoute: typeof FrontendRoute
  MatchmakingRoute: typeof MatchmakingRoute
  ProblemsRoute: typeof ProblemsRoute
  ResultRoute: typeof ResultRoute
  SqlRoute: typeof SqlRoute
  Web3Route: typeof Web3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web3': {
      id: '/web3'
      path: '/web3'
      fullPath: '/web3'
      preLoaderRoute: typeof Web3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaking': {
      id: '/matchmaking'
      path: '/matchmaking'
      fullPath: '/matchmaking'
      preLoaderRoute: typeof MatchmakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontend': {
      id: '/frontend'
      path: '/frontend'
      fullPath: '/frontend'
      preLoaderRoute: typeof FrontendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotherPage': {
      id: '/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotherPageRoute: AnotherPageRoute,
  BuyRoute: BuyRoute,
  FrontendRoute: FrontendRoute,
  MatchmakingRoute: MatchmakingRoute,
  ProblemsRoute: ProblemsRoute,
  ResultRoute: ResultRoute,
  SqlRoute: SqlRoute,
  Web3Route: Web3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
